// Governing: ADR-0007 (Scrape the Full Hunter Roster into a Generated Dataset), SPEC-0003
// REQ "Favorite Hunters", SPEC-0003 Security Requirements "Request Body Size Limits"
// ("`hunterId` SHALL be length-capped and validated against the known library")
//
// The server's read-only view of the hunter roster, for validating a `hunterId` a client
// asks to favorite.
//
// The roster lives at the repo root in `data/hunters.json`, a SHARED artifact both
// workspaces import. It used to sit inside the client workspace and be read across the
// workspace boundary from here; that arrangement built fine and tested fine but did not
// survive packaging — the Docker runtime stage never copies `client/src`, so in a real
// image this read found nothing and every favorite write AND delete returned 400. Root
// `data/` is copied explicitly by both the client build stage and the runtime stage, which
// is what makes the file a deployable artifact rather than an accident of the source tree.
// There is still exactly one file and one answer to "is this a known hunter".
//
// It is read with fs rather than an `import ... with { type: "json" }` on purpose: the JSON
// import attribute is still flagged experimental on Node 20 and prints a warning on every
// boot, and a plain read lets the failure be reported with the resolved path.

import { readFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));

// server/src/lib -> repo root -> data/hunters.json
const ROSTER_FILE = path.join(__dirname, "..", "..", "..", "data", "hunters.json");

/**
 * Read the roster, or die trying.
 *
 * FATAL AT BOOT, deliberately — and note this is the OPPOSITE of `db.js`, which catches a
 * bad data file and starts with empty collections. The two files are not the same kind of
 * thing:
 *
 *   - `db.json` is MUTABLE USER DATA on a mounted volume. It can be damaged at runtime by
 *     something outside the image, a redeploy will not repair it, and crash-looping on it
 *     takes the whole app down over one bad record. Degrading is right there.
 *   - `hunters.json` is an IMMUTABLE COMMITTED BUILD ASSET. If it is missing or unparseable
 *     the image is mis-packaged, nothing the process does at runtime can fix it, and only a
 *     rebuild will. Degrading there bought a permanently broken feature that reported
 *     itself as healthy: `/healthz` stayed 200, every PUT and DELETE returned 400 "unknown
 *     hunter" — indistinguishable from a stale client — and the one boot log line naming
 *     the real cause scrolled away. Refusing to boot turns that into a deploy that fails
 *     loudly on its first run.
 *
 * The VALIDATION stays fail-closed regardless: an id absent from a roster that DID load is
 * still rejected. What changes is the lifecycle, not the verdict.
 */
function loadRosterIds() {
  let parsed;
  try {
    parsed = JSON.parse(readFileSync(ROSTER_FILE, "utf8"));
  } catch (err) {
    throw new Error(
      `unable to read the hunter roster at ${ROSTER_FILE}: ${err.message}. ` +
        "This file is generated by `node scripts/scrape-hunters.mjs` and committed; if this " +
        "is a container, the image is missing `COPY data data`.",
      { cause: err }
    );
  }
  if (!Array.isArray(parsed)) {
    throw new Error(`hunter roster at ${ROSTER_FILE} is not a JSON array`);
  }
  const ids = new Set(parsed.map((h) => h?.id).filter((id) => typeof id === "string" && id));
  if (ids.size === 0) {
    throw new Error(`hunter roster at ${ROSTER_FILE} carries no usable hunter ids`);
  }
  return ids;
}

const HUNTER_IDS = loadRosterIds();

/** How many hunters the roster carried at boot. Exported so a test can assert it loaded. */
export const rosterSize = () => HUNTER_IDS.size;

/** True when `id` names a hunter in the generated dataset. */
export function isKnownHunterId(id) {
  return typeof id === "string" && HUNTER_IDS.has(id);
}
